services:
  - type: web
    name: extrator-api
    env: python
    plan: free # Usa o plano gratuito do Render
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 # Usando uma versão estável suportada pelo Render